---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/

---
spring:
  profiles: subject
words: I,You,He,She,It
  
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
  
  
 gfApp.controller("gfDataCtrl",function($scope,$log,$http){
	$scope.hasData = false;
	$scope.hasImage = false;
	$scope.hasErrors = false;
	$scope.formData={};
	$scope.formData.port="10334";
	$scope.formData.pdxStore="PdxStore";
	$scope.formData.host="sd-86c4-4f11.nam.nsroot.net";
	$scope.logger=function(type,mesg){
		if(type == "INFO"){
			$log.info(mesg);
		}
		if(type == "WARN"){
			$log.warn(mesg);
		}
		if(type == "ERROR"){
			$log.error(mesg);
		}
	};
	$scope.getData=function(){
		var gfData="";
		$scope.hasData = false;
		$scope.hasErrors = false;
		$scope.logger("INFO",$scope.formData);

		$http.post('/mydata',
			{
			host:$scope.formData.host,
			port:$scope.formData.port,
			region:$scope.formData.region,
			pdxStore:$scope.formData.pdxStore,
			key:$scope.formData.key,
			clearRegion:$scope.formData.clearRegion,
			password:$scope.formData.auth,
			})
		.then(function success(response){
			gfData = response.data;
			$scope.errors = gfData.errors;
			if(angular.isObject(gfData.data) && (gfData.data.length > 0)){
				$scope.data = gfData.data;
				$scope.hasData = true;
			}

			if(gfData.dataImage === null ){
				$scope.hasImage = false;
			}else{
				$scope.dataImage = gfData.dataImage;
				$scope.hasImage = true;
			}
			
			if(angular.isObject(gfData.errors) && (gfData.errors.length > 0)){
				$scope.hasErrors = true;
			}
		},function error(response){
			$scope.errorData=response.data;
		});
		
		$scope.formData.clearRegion = false;
		$scope.formData.auth = "";
		
	};
});
