---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/

---
spring:
  profiles: subject
words: I,You,He,She,It
  
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
  







------------------------------------------------------------------------------------------------------------------
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<title>Hazelcast Data Extract Utility</title>
</head>

<body>

<div ng-app="hazelcastApp" ng-controller="hazelcastCtrl">

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<nav class="navbar navbar-default">
				<div class="container-fluid">
					<div class="navbar-header">
						<a class="navbar-brand" href="#">Hazelcast Trouble-shooting Tool</a>
					</div>
				</div>
			</nav>
		</div>
	</div>
	<div class="row ">
		<div class="col-md-12">
			<div class="panel panel-primary">
					<div class="panel-heading">Search</div>
					<div class="panel-body">
 
						<div class="container">
						  <form class="form-horizontal" role="form" name="cacheForm" id="cacheForm" (ngSubmit)="onSubmit()" #cacheForm="ngForm">
						  	<div class="row">
							    <div class="form-group">
							      <label class="control-label col-sm-1" for="mapkey">Map Key:</label>
							      <div class="col-sm-3">
									<select class="form-control" (change)="onCacheChanged($event)">
										<option value="none">Select</option>
										<option value="allcache">All Cache</option>
										<option value="membercache">Member Cache</option>
										<option value="customercache">Customer Cache</option>
										<option value="keycache">Key Cache</option>
									</select>

							      </div>
							      <label class="control-label col-sm-1" for="serverid">Server Id:</label>
							      <div class="col-sm-1">          
							        <input type="text" class="form-control" [disabled]="allCacheEnabled" [required]='!allCacheEnabled' id="serverid" ng-model="formData.serverid" placeholder="127.0.0.1:8080" >
							      </div>
							      <label class="control-label col-sm-1" for="releaseid">Release Id:</label>
							      <div class="col-sm-3">          
							        <input type="text" class="form-control" [disabled]="allCacheEnabled" [required]='!allCacheEnabled' id="releaseid" ng-model="formData.releaseid" placeholder="20180505">
									<div [hidden]="isValidReleaseid" class="alert alert-danger">Release Id is required</div>
							      </div>
							    </div>
						  	</div>
						  	<div class="row">
							    <div class="form-group">
							      <label class="control-label col-sm-1" for="directory">Directory:</label>
							      <div class="col-sm-3">
									<select class="form-control" 
										ng-model="formData.directory">
										<option value="test1">test1</option>
										<option value="test2">test2</option>
									</select>
							      </div>
							      <label class="control-label col-sm-1" for="memberid">Member Id:</label>
							      <div class="col-sm-5">          
							        <input type="text" class="form-control" id="memberid" [disabled]="allCacheEnabled" [required]='!allCacheEnabled' 
</div>		
</div>
</body>

</html>


import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  allCacheEnabled = false;
  isValidReleaseid = true;
  submitted = false;
  isValidReleaseid = true;
 
 onCacheChanged(event: any) {
	 this.allCacheEnabled = (event.target.value == 'allcache');
 } 
 onSubmit() {
	  this.submitted = true;
	  if(!this.allCacheEnabled){
		  
	  }
  }
}
