---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/

---
spring:
  profiles: subject
words: I,You,He,She,It
  
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
  
  ---
  app.component.html
<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <h1>
    Welcome to {{ title }}!
  </h1>
 </div>

<select class='select-option' required [(ngModel)]='optionSelected' (ngModelChange)='onOptionSelected($event)'>
    <option class='option' *ngFor='let option of options' [value]="option">{{option}}</option>
</select>

<select class='select-option-1'  [disabled]="firstOptionDisabled" required >
    <option class='option' *ngFor='let option of options' [value]="option">{{option}}</option>
</select>

<select class='select-option-2' [disabled]="secondOptionDisabled" required>
    <option class='option' *ngFor='let option of options' [value]="option">{{option}}</option>
</select>


app.component.ts

import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  options = [1, 2, 'All','none'];
 optionSelected: any;
 subOptionSelected: any;
 subOptionSelected: any;
 firstOptionDisabled = false;
 secondOptionDisabled = false;
 
 
 onOptionSelected(event){
	switch (event) {
		case '1':
			this.firstOptionDisabled = true;
			this.secondOptionDisabled = false;
			break;
		case '2':
			this.firstOptionDisabled = false;
			this.secondOptionDisabled = true;
			break;
		case 'none':
			this.firstOptionDisabled = false;
			this.secondOptionDisabled = false;
			break;
		default:
			this.secondOptionDisabled = true;
			this.firstOptionDisabled = true;
			break;
	}
}
 
}
